FROM node:22.21.1-alpine AS build

WORKDIR /app

COPY server/package*.json ./

RUN npm install

COPY server/ ./

RUN npm run build

FROM node:22.21.1-alpine

WORKDIR /app

COPY --from=build /app/dist ./dist

EXPOSE 8080

ENV NODE_ENV=production

CMD ["node", "dist/index.js"]
